apiVersion: apps/v1
kind: Deployment
metadata:
  name: reports
  namespace: ledgers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reports
  template:
    metadata:
      labels:
        app: reports
    spec:
      containers:
        - name: reports
          image: reports:1.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: dynamic-reports-config