apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights
  namespace: ledgers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insights
  template:
    metadata:
      labels:
        app: insights
    spec:
      containers:
        - name: insights
          image: insights:1.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: dynamic-insights-config